### ISSUE TITLE
Create demo API file

### ISSUE THREAD

**Issue by mjclawar** [StratoDem/strato-query#13]
## Description

Add demo API queries that can be shared, either as a markdown file or as a Python file

## User Story

As a StratoDem Analytics client, I would like to see a few sample queries using `strato_query` objects so I can model my own API queries off of them.

## Sub-tasks

- [x] Median household income for 80+ households query structure
- [x] Population density query structure
- [x] Number of households age 25 to 39 with net worth of at least $50,000 within 20-minute drive

**Comment by coralvanda** [comment]
Would the markdown file be an example of the JSON form of the queries?

**Comment by mjclawar** [comment]
Thinking something like what's already here: https://github.com/StratoDem/strato-query#example-use-of-query-base-class-with-api-call-and-example-filter

Plus potentially the JSON output.
