### ISSUE TITLE
Add retries for queries that experience connection issues

### ISSUE THREAD

**Issue by coralvanda** [StratoDem/strato-query#39]
## Description

We want to add resiliency by retrying queries after connection failures with increasing time between tries. Only after several retries should the package raise a connection error.
## User Story

As a user, I don't want a query to fail immediately if there is a hiccup in the network.

## Sub-tasks

- [x] Identify locations where a network issue could cause a failure
- [x] Determine which errors should result in a retry, and which, if any, should be raised immediately
- [x] Wrap the appropriate code in `try` blocks and have it sleep and retry depending on the error
- [x] Test
